./target/release/node-template \
--base-path /tmp/node01 \
--chain ./testNetSpecRaw.json \
--port 30333 \
--ws-port 9944 \
--rpc-port 9933 \
--telemetry-url "wss://telemetry.polkadot.io/submit/ 0" \
--validator \
--rpc-cors all \
--ws-external \
--rpc-external \
--rpc-methods Unsafe \
--name MyNode01
